import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { api } from '../../services/api';
import { Resume } from '../../types';
import {
  Sparkles,
  ArrowLeft,
  CheckCircle2,
  AlertCircle,
  Code2,
  FolderGit2,
  Layers,
  ArrowRight,
} from 'lucide-react';

export const ResumeRecommendationsPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const [resume, setResume] = useState<Resume | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (id) {
      api
        .getResumeById(id)
        .then((res) => setResume(res.resume))
        .catch((err) => console.warn(err))
        .finally(() => setLoading(false));
    }
  }, [id]);

  if (loading) {
    return <div className="p-8 text-center text-xs text-slate-500">Loading recommendations...</div>;
  }

  if (!resume) {
    return <div className="p-8 text-center text-xs text-red-500">Resume not found</div>;
  }

  const rec = resume.recommendations || {
    resumeImprovements: [
      'Incorporate more quantitative benchmarks in project descriptions.',
      'Highlight modern distributed caching (Redis) or message queues.',
    ],
    missingSkills: ['Redis', 'Docker', 'Kubernetes', 'CI/CD Pipelines'],
    suggestedProjects: [
      {
        title: 'Distributed Event Queue & Cache Proxy',
        description: 'Design and deploy an asynchronous job queuing mechanism with Redis Streams.',
        techStack: ['TypeScript', 'Node.js', 'Redis', 'Docker'],
        careerImpact: 'Demonstrates deep backend scaling competence valued by tier-1 tech firms.',
      },
    ],
    strengths: ['High technical keyword density', 'Well-structured education and internship metrics'],
    weaknesses: ['Limited mention of automated testing pipelines'],
    careerReadinessSuggestions: ['Ready for Mid-Level Full-Stack software engineering rounds.'],
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <Link
            to={`/student/resumes/${resume.id}/diagnostic`}
            className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-600 hover:text-slate-900 mb-2"
          >
            <ArrowLeft className="w-4 h-4" /> Back to Diagnostic
          </Link>
          <h1 className="text-2xl font-extrabold text-slate-900 tracking-tight">AI Resume Improvement &amp; Projects</h1>
          <p className="text-xs text-slate-500 mt-1">
            Personalized recommendations generated by Gemini 3.8 Flash based on your parsed competencies.
          </p>
        </div>

        <Link
          to="/student/career-guidance/roadmap"
          className="inline-flex items-center gap-2 px-4 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-bold transition-all shadow-xs"
        >
          <Layers className="w-4 h-4" /> View 30-60-90 Roadmap
        </Link>
      </div>

      {/* Advisory Banner */}
      <div className="p-4 bg-indigo-50/70 border border-indigo-100 rounded-2xl text-xs text-indigo-950 flex items-start gap-3">
        <Sparkles className="w-4 h-4 text-indigo-600 flex-shrink-0 mt-0.5" />
        <p>
          <span className="font-bold">Advisory Notice:</span> Generated recommendations and project concepts are designed
          to close demonstrable portfolio gaps. They do not constitute official company endorsements or guaranteed offers.
        </p>
      </div>

      {/* Key Improvements */}
      <div className="bg-white border border-slate-200/80 rounded-2xl p-6 shadow-xs space-y-3">
        <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400">
          Targeted Resume Optimizations
        </h2>
        <div className="space-y-2.5">
          {rec.resumeImprovements.map((item, i) => (
            <div key={i} className="flex items-start gap-3 p-3 bg-slate-50 rounded-xl border border-slate-100 text-xs text-slate-800">
              <span className="w-5 h-5 rounded-full bg-indigo-100 text-indigo-700 font-bold flex items-center justify-center flex-shrink-0 text-[10px]">
                {i + 1}
              </span>
              <span>{item}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Missing Skills */}
      <div className="bg-white border border-slate-200/80 rounded-2xl p-6 shadow-xs space-y-3">
        <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400 flex items-center gap-1.5">
          <Code2 className="w-4 h-4 text-indigo-600" /> Recommended High-Impact Skills to Acquire
        </h2>
        <p className="text-xs text-slate-500">
          Adding these technologies to your portfolio will unlock eligibility for 40%+ more mid-level engineering positions.
        </p>
        <div className="flex flex-wrap gap-2 pt-1">
          {rec.missingSkills.map((skill) => (
            <span
              key={skill}
              className="px-3 py-1.5 bg-amber-50 text-amber-900 border border-amber-200 rounded-xl text-xs font-bold flex items-center gap-1.5"
            >
              <span className="w-1.5 h-1.5 rounded-full bg-amber-500" />
              {skill}
            </span>
          ))}
        </div>
      </div>

      {/* Recommended Capstone Projects */}
      <div className="bg-white border border-slate-200/80 rounded-2xl p-6 shadow-xs space-y-4">
        <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400 flex items-center gap-1.5">
          <FolderGit2 className="w-4 h-4 text-indigo-600" /> Recommended Portfolio Upgrade Projects
        </h2>

        <div className="space-y-4">
          {rec.suggestedProjects.map((proj, i) => (
            <div key={i} className="p-5 bg-slate-50 rounded-2xl border border-slate-200/80 space-y-3">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1">
                <h3 className="text-sm font-bold text-slate-900">{proj.title}</h3>
                <div className="flex flex-wrap gap-1">
                  {proj.techStack.map((tech) => (
                    <span key={tech} className="text-[10px] bg-white px-2 py-0.5 rounded border border-slate-200 font-mono text-slate-600">
                      {tech}
                    </span>
                  ))}
                </div>
              </div>

              <p className="text-xs text-slate-700 leading-relaxed">{proj.description}</p>

              <div className="p-2.5 bg-indigo-50/80 rounded-xl border border-indigo-100 text-xs text-indigo-900 font-medium">
                🎯 Career Impact: {proj.careerImpact}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
